// <auto-generated />
using System;
using FlexPos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlexPos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlexPosDbContext))]
    [Migration("20261003154602_AgregarConfiguracionYAdministracionUsuarios")]
    partial class AgregarConfiguracionYAdministracionUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flexpos")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlexPos.Domain.Entities.ConfiguracionNegocio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoMoneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("codigo_moneda");

                    b.Property<bool>("ComisionProductosHabilitada")
                        .HasColumnType("boolean")
                        .HasColumnName("comision_productos_habilitada");

                    b.Property<string>("Correo")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correo");

                    b.Property<Guid?>("CreadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por_id");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_principal");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<string>("IdentificacionFiscal")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("identificacion_fiscal");

                    b.Property<Guid?>("ModificadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificado_por_id");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_comercial");

                    b.Property<bool>("PermitirVentaSinStock")
                        .HasColumnType("boolean")
                        .HasColumnName("permitir_venta_sin_stock");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Telefono")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("telefono");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EsPrincipal")
                        .IsUnique()
                        .HasDatabaseName("ux_configuracion_negocio_principal")
                        .HasFilter("es_principal = true");

                    b.ToTable("configuracion_negocio", "flexpos");
                });

            modelBuilder.Entity("FlexPos.Domain.Entities.ImpuestoConfigurado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<Guid>("ConfiguracionNegocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("configuracion_negocio_id");

                    b.Property<Guid?>("CreadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por_id");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<Guid?>("ModificadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificado_por_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_normalizado");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionNegocioId", "NombreNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ux_impuestos_configuracion_nombre");

                    b.ToTable("impuestos", "flexpos");
                });

            modelBuilder.Entity("FlexPos.Domain.Entities.MetodoPagoConfigurado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<Guid>("ConfiguracionNegocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("configuracion_negocio_id");

                    b.Property<Guid?>("CreadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por_id");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<Guid?>("ModificadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificado_por_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre_normalizado");

                    b.Property<bool>("RequiereReferencia")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_referencia");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionNegocioId", "NombreNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ux_metodos_pago_configuracion_nombre");

                    b.ToTable("metodos_pago", "flexpos");
                });

            modelBuilder.Entity("FlexPos.Domain.Entities.NumeracionDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConfiguracionNegocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("configuracion_negocio_id");

                    b.Property<Guid?>("CreadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por_id");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<Guid?>("ModificadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificado_por_id");

                    b.Property<string>("Prefijo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prefijo");

                    b.Property<long>("SiguienteNumero")
                        .HasColumnType("bigint")
                        .HasColumnName("siguiente_numero");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_documento");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionNegocioId", "TipoDocumento")
                        .IsUnique()
                        .HasDatabaseName("ux_numeraciones_documento_tipo");

                    b.ToTable("numeraciones_documento", "flexpos");
                });

            modelBuilder.Entity("FlexPos.Domain.Entities.TokenRenovacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por_id");

                    b.Property<DateTimeOffset>("CreadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_utc");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<Guid?>("ModificadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificado_por_id");

                    b.Property<string>("ReemplazadoPorHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reemplazado_por_hash");

                    b.Property<DateTimeOffset?>("RevocadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocado_utc");

                    b.Property<string>("SelloSeguridad")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sello_seguridad");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTimeOffset>("VenceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vence_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_tokens_renovacion_hash");

                    b.HasIndex("UsuarioId", "RevocadoUtc")
                        .HasDatabaseName("ix_tokens_renovacion_usuario_activos");

                    b.ToTable("tokens_renovacion", "flexpos");
                });

            modelBuilder.Entity("FlexPos.Infrastructure.Identity.RolIdentidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("sello_concurrencia");

                    b.Property<Guid?>("CreadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por_id");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<Guid?>("ModificadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificado_por_id");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nombre");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nombre_normalizado");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "flexpos");
                });

            modelBuilder.Entity("FlexPos.Infrastructure.Identity.UsuarioIdentidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("intentos_fallidos");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<bool>("CambioContrasenaObligatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("cambio_contrasena_obligatorio");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("sello_concurrencia");

                    b.Property<Guid?>("CreadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por_id");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correo");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("correo_confirmado");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("bloqueo_habilitado");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin_bloqueo_utc");

                    b.Property<Guid?>("ModificadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificado_por_id");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correo_normalizado");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nombre_usuario_normalizado");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("hash_contrasena");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("telefono_confirmado");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("sello_seguridad");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("doble_factor_habilitado");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nombre_usuario");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_usuarios_correo_normalizado");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("usuarios", "flexpos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("reclamaciones_rol", "flexpos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("reclamaciones_usuario", "flexpos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("proveedor");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("clave_proveedor");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("nombre_proveedor");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("inicios_sesion_externos", "flexpos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("usuarios_roles", "flexpos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("proveedor");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("tokens_usuario", "flexpos");
                });

            modelBuilder.Entity("FlexPos.Domain.Entities.ImpuestoConfigurado", b =>
                {
                    b.HasOne("FlexPos.Domain.Entities.ConfiguracionNegocio", null)
                        .WithMany()
                        .HasForeignKey("ConfiguracionNegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FlexPos.Domain.Entities.MetodoPagoConfigurado", b =>
                {
                    b.HasOne("FlexPos.Domain.Entities.ConfiguracionNegocio", null)
                        .WithMany()
                        .HasForeignKey("ConfiguracionNegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FlexPos.Domain.Entities.NumeracionDocumento", b =>
                {
                    b.HasOne("FlexPos.Domain.Entities.ConfiguracionNegocio", null)
                        .WithMany()
                        .HasForeignKey("ConfiguracionNegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FlexPos.Domain.Entities.TokenRenovacion", b =>
                {
                    b.HasOne("FlexPos.Infrastructure.Identity.UsuarioIdentidad", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("FlexPos.Infrastructure.Identity.RolIdentidad", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FlexPos.Infrastructure.Identity.UsuarioIdentidad", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FlexPos.Infrastructure.Identity.UsuarioIdentidad", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("FlexPos.Infrastructure.Identity.RolIdentidad", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlexPos.Infrastructure.Identity.UsuarioIdentidad", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FlexPos.Infrastructure.Identity.UsuarioIdentidad", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
